### PR TITLE
#11 shimmer

### PR DESCRIPTION
**Pull request by Nowele**
This PR is to resolve issue #11 : 

* Added ShimmerActivity and implemented Shimmer effect in its layout.

* Added the library name to the ArrayList in the LibrariesFragment.

* Created an intent to the activity in the LibrariesAdapter(RecyclerView Adapter) for the new library case.

* Add my name Name, Github ID, and LinkedIn ID to the contributors ArrayList in the ContributorsFragment. 

* I also created string resources and a Constants file to reduce hardcoded strings

### CODE REVIEW

**Comment by Nowele** [comment]
Can you please add "hacktoberfest-accepted" label?

**Comment by DhaneshShetty** [comment]
@Nowele LGTM!Great work...
**Note:** Please work on only one issue in one PR.If you find any issue in the app,you are free to create an issue on github(if it is not listed) and claim that. A contributor is allowed to work on one issue at a time.Please send the PR once you are assigned to the issue.

**Comment by DhaneshShetty** [comment]
@Nowele For your PR to be merged send a new PR for only the shimmer issue.

**Comment by DineshBS44** [comment]
@Nowele, you are only allowed to add the new strings added by you which will be shown in the UI in strings.xml file (For example the strings added in the shimmer activity). The other hardcoded strings are not to be added in the strings.xml file as it is a separate issue. Your PR has been labelled as "hacktoberfest-accepted". If you want the PR to be merged too, please send a new Pull Request only for the Shimmer issue as mentioned.

**Comment by Nowele** [comment]
Fixed here: https://github.com/ACM-VIT/libground/pull/19

**Pull request closed without merging**
