### PR TITLE
Implement Retrofit Library

### PR DESCRIPTION
**Pull request by alvintan05**
PR to solve issue #12 

- Create a new Activity and implement RetroFit. 
- Add the library name to the ArrayList in the LibrariesFragment. 
- Create an intent to the activity in the LibrariesAdapter(RecyclerView Adapter) 
- Add your Name, Github id and LinkedIn ID to the contributors ArrayList in the ContributorsFragment.

### CODE REVIEW

**Comment by alvintan05** [comment]
Hi @DineshBS44 , this is the latest change, could you check this pr ?

**Comment by DhaneshShetty** [comment]
Great work @alvintan05 .Thanks for contributing!

**Comment by alvintan05** [comment]
@DhaneshShetty You're welcome, could you give this pr hacktoberfest-accepted label ? Thank you

**Comment by DhaneshShetty** [comment]
> @DhaneshShetty You're welcome, could you give this pr hacktoberfest-accepted label ? Thank you

@alvintan05 As this repository has hacktoberfest label,any PR merged into it will be counted towards hacktoberfest. There is no need of hacktoberfest-accepted label.

**Pull request merged**
